#!/bin/bash
# Google Cloud Storage Migration Script
# Generated by: python manage.py audit_contract_files --export

BUCKET_NAME="contract-analyzer-media"
MEDIA_ROOT="/Users/emil.aliyev/My Projects/Cont_pars/media"

echo "=== Migrating Contract Files to GCS ==="
echo "Total files to migrate: 68"

echo "Uploading 1/68: contracts/SIGNED-_Madu_BSA_AML_Independent_Audit_mX3QQcz.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED-_Madu_BSA_AML_Independent_Audit_mX3QQcz.pdf" "gs://$BUCKET_NAME/contracts/SIGNED-_Madu_BSA_AML_Independent_Audit_mX3QQcz.pdf"

echo "Uploading 2/68: contracts/SIGNED_-_6Lock_MULTIYEAR_AML_IA_2025_KKHWRon.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_6Lock_MULTIYEAR_AML_IA_2025_KKHWRon.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_6Lock_MULTIYEAR_AML_IA_2025_KKHWRon.pdf"

echo "Uploading 3/68: contracts/SIGNED_-_6lock_ACH_Audit_P8Sd9oi.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_6lock_ACH_Audit_P8Sd9oi.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_6lock_ACH_Audit_P8Sd9oi.pdf"

echo "Uploading 4/68: contracts/SIGNED_-_ANT_AUS_AML_Program_Review_I45Elkg.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_ANT_AUS_AML_Program_Review_I45Elkg.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_ANT_AUS_AML_Program_Review_I45Elkg.pdf"

echo "Uploading 5/68: contracts/SIGNED_-_ANT_INTERNATIONAL_AML_Program_Review_95MTGQZ.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_ANT_INTERNATIONAL_AML_Program_Review_95MTGQZ.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_ANT_INTERNATIONAL_AML_Program_Review_95MTGQZ.pdf"

echo "Uploading 6/68: contracts/SIGNED_-_APM_Help_Compliance_Build_Out_EVPxAOB.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_APM_Help_Compliance_Build_Out_EVPxAOB.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_APM_Help_Compliance_Build_Out_EVPxAOB.pdf"

echo "Uploading 7/68: contracts/SIGNED_-_Anrok_BSA_AML_IA_KzHFMVz.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Anrok_BSA_AML_IA_KzHFMVz.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Anrok_BSA_AML_IA_KzHFMVz.pdf"

echo "Uploading 8/68: contracts/SIGNED_-_Athena_Compliance_Program_Buildout_1BjnvxI.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Athena_Compliance_Program_Buildout_1BjnvxI.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Athena_Compliance_Program_Buildout_1BjnvxI.pdf"

echo "Uploading 9/68: contracts/SIGNED_-_Blockchain_TM-2025_fwfmQ0l.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Blockchain_TM-2025_fwfmQ0l.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Blockchain_TM-2025_fwfmQ0l.pdf"

echo "Uploading 10/68: contracts/SIGNED_-_Booking_JOo6e5J.com_BHFS_MPP_Onboarding_Operations_Support.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Booking_JOo6e5J.com_BHFS_MPP_Onboarding_Operations_Support.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Booking_JOo6e5J.com_BHFS_MPP_Onboarding_Operations_Support.pdf"

echo "Uploading 11/68: contracts/SIGNED_-_ByteDance_MSA_CT20250_clCZs5G.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_ByteDance_MSA_CT20250_clCZs5G.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_ByteDance_MSA_CT20250_clCZs5G.pdf"

echo "Uploading 12/68: contracts/SIGNED_-_ByteDance_Sanctions_Model_Validation_Hxcrw1B.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_ByteDance_Sanctions_Model_Validation_Hxcrw1B.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_ByteDance_Sanctions_Model_Validation_Hxcrw1B.pdf"

echo "Uploading 13/68: contracts/SIGNED_-_Chime_BSA_AML_Independent_Review_Tn2msvk.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Chime_BSA_AML_Independent_Review_Tn2msvk.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Chime_BSA_AML_Independent_Review_Tn2msvk.pdf"

echo "Uploading 14/68: contracts/SIGNED_-_Circle_DFS_504_Readiness_Review_NhFAelQ.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Circle_DFS_504_Readiness_Review_NhFAelQ.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Circle_DFS_504_Readiness_Review_NhFAelQ.pdf"

echo "Uploading 15/68: contracts/SIGNED_-_Clara_BSA_AML_Independent_Assessment_2025_DTGflzB.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Clara_BSA_AML_Independent_Assessment_2025_DTGflzB.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Clara_BSA_AML_Independent_Assessment_2025_DTGflzB.pdf"

echo "Uploading 16/68: contracts/SIGNED_-_Clara_Compliance_Buildout_2025_Extension_Vlo9ohU.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Clara_Compliance_Buildout_2025_Extension_Vlo9ohU.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Clara_Compliance_Buildout_2025_Extension_Vlo9ohU.pdf"

echo "Uploading 17/68: contracts/SIGNED_-_Clara_LMS_Ww4ubiF.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Clara_LMS_Ww4ubiF.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Clara_LMS_Ww4ubiF.pdf"

echo "Uploading 18/68: contracts/SIGNED_-_Coinbase_-_Ops_Support_Jun2025_QO5BHJy.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Coinbase_-_Ops_Support_Jun2025_QO5BHJy.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Coinbase_-_Ops_Support_Jun2025_QO5BHJy.pdf"

echo "Uploading 19/68: contracts/SIGNED_-_Coinbase_Apr_2024_Ops_Support_I8Kgweh.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Coinbase_Apr_2024_Ops_Support_I8Kgweh.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Coinbase_Apr_2024_Ops_Support_I8Kgweh.pdf"

echo "Uploading 20/68: contracts/SIGNED_-_Coinbase_Ops_Support_2025_4sFEuZV.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Coinbase_Ops_Support_2025_4sFEuZV.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Coinbase_Ops_Support_2025_4sFEuZV.pdf"

echo "Uploading 21/68: contracts/SIGNED_-_Coinbase_Ops_Support_Jul2025_i5mFZks.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Coinbase_Ops_Support_Jul2025_i5mFZks.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Coinbase_Ops_Support_Jul2025_i5mFZks.pdf"

echo "Uploading 22/68: contracts/SIGNED_-_Coinbase_Ops_Support_Ph2_abpQtUM.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Coinbase_Ops_Support_Ph2_abpQtUM.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Coinbase_Ops_Support_Ph2_abpQtUM.pdf"

echo "Uploading 23/68: contracts/SIGNED_-_Conduit_Addendum_Staff_Aug_MCpThMY.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Conduit_Addendum_Staff_Aug_MCpThMY.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Conduit_Addendum_Staff_Aug_MCpThMY.pdf"

echo "Uploading 24/68: contracts/SIGNED_-_Conduit_Compliance_Program_Remediation__Enhancement_SCDxCU4.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Conduit_Compliance_Program_Remediation__Enhancement_SCDxCU4.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Conduit_Compliance_Program_Remediation__Enhancement_SCDxCU4.pdf"

echo "Uploading 25/68: contracts/SIGNED_-_Conduit_Compliance_Program_Review_N44Drhp.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Conduit_Compliance_Program_Review_N44Drhp.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Conduit_Compliance_Program_Review_N44Drhp.pdf"

echo "Uploading 26/68: contracts/SIGNED_-_Conduit_Hawk_and_Scorechain_Tuning_V3pJnX2.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Conduit_Hawk_and_Scorechain_Tuning_V3pJnX2.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Conduit_Hawk_and_Scorechain_Tuning_V3pJnX2.pdf"

echo "Uploading 27/68: contracts/SIGNED_-_Corpay_CDD_and_AML_Remediation_Support_B20TeR2.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Corpay_CDD_and_AML_Remediation_Support_B20TeR2.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Corpay_CDD_and_AML_Remediation_Support_B20TeR2.pdf"

echo "Uploading 28/68: contracts/SIGNED_-_Corpay_EDD_Staff_Aug_11781iD.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Corpay_EDD_Staff_Aug_11781iD.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Corpay_EDD_Staff_Aug_11781iD.pdf"

echo "Uploading 29/68: contracts/SIGNED_-_Corpay_Screening_Tuning_and_DQ_wbnW66f.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Corpay_Screening_Tuning_and_DQ_wbnW66f.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Corpay_Screening_Tuning_and_DQ_wbnW66f.pdf"

echo "Uploading 30/68: contracts/SIGNED_-_Cumberland_DRW_Ops_Support_BTyZCAd.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Cumberland_DRW_Ops_Support_BTyZCAd.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Cumberland_DRW_Ops_Support_BTyZCAd.pdf"

echo "Uploading 31/68: contracts/SIGNED_-_DRW_Staff_Aug_RGAMKdh.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_DRW_Staff_Aug_RGAMKdh.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_DRW_Staff_Aug_RGAMKdh.pdf"

echo "Uploading 32/68: contracts/SIGNED_-_Deel_AML_TM_Sardine_Implementation_Support_Ph1_EqVL2cd.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Deel_AML_TM_Sardine_Implementation_Support_Ph1_EqVL2cd.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Deel_AML_TM_Sardine_Implementation_Support_Ph1_EqVL2cd.pdf"

echo "Uploading 33/68: contracts/SIGNED_-_Dots_LMS_Training_Licenses_06_PcsoLF2.23.2025.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Dots_LMS_Training_Licenses_06_PcsoLF2.23.2025.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Dots_LMS_Training_Licenses_06_PcsoLF2.23.2025.pdf"

echo "Uploading 34/68: contracts/SIGNED_-_Equitrack_Compliance_Program_Buildout_BA6iB2X.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Equitrack_Compliance_Program_Buildout_BA6iB2X.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Equitrack_Compliance_Program_Buildout_BA6iB2X.pdf"

echo "Uploading 35/68: contracts/SIGNED_-_FFB_Hawk_Implementation_vvaozuI.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_FFB_Hawk_Implementation_vvaozuI.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_FFB_Hawk_Implementation_vvaozuI.pdf"

echo "Uploading 36/68: contracts/SIGNED_-_Flyra_Compliance_Program_Buildout_p7Jq5Iv.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Flyra_Compliance_Program_Buildout_p7Jq5Iv.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Flyra_Compliance_Program_Buildout_p7Jq5Iv.pdf"

echo "Uploading 37/68: contracts/SIGNED_-_Gemini_Sanctions_Model_Validation_mn0JaDq.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Gemini_Sanctions_Model_Validation_mn0JaDq.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Gemini_Sanctions_Model_Validation_mn0JaDq.pdf"

echo "Uploading 38/68: contracts/SIGNED_-_Hamilton_Compliance_Program_Buildout_0IYbjuH.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Hamilton_Compliance_Program_Buildout_0IYbjuH.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Hamilton_Compliance_Program_Buildout_0IYbjuH.pdf"

echo "Uploading 39/68: contracts/SIGNED_-_HomeTrust_Bank_-_AML_Operational_Support_KZ0s0Ro.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_HomeTrust_Bank_-_AML_Operational_Support_KZ0s0Ro.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_HomeTrust_Bank_-_AML_Operational_Support_KZ0s0Ro.pdf"

echo "Uploading 40/68: contracts/SIGNED_-_House_Of_Doge_Retainer_Agreement_oqaaZeY.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_House_Of_Doge_Retainer_Agreement_oqaaZeY.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_House_Of_Doge_Retainer_Agreement_oqaaZeY.pdf"

echo "Uploading 41/68: contracts/SIGNED_-_Kraken_FIU_Review_Change_Order_VHMk3Zu.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Kraken_FIU_Review_Change_Order_VHMk3Zu.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Kraken_FIU_Review_Change_Order_VHMk3Zu.pdf"

echo "Uploading 42/68: contracts/SIGNED_-_Lithic_Fraud_Audit_Multi_Year_8IAIoB6.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Lithic_Fraud_Audit_Multi_Year_8IAIoB6.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Lithic_Fraud_Audit_Multi_Year_8IAIoB6.pdf"

echo "Uploading 43/68: contracts/SIGNED_-_Marqeta_Transaction_Monitoring_Tuning_Support_2025.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Marqeta_Transaction_Monitoring_Tuning_Support_2025.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Marqeta_Transaction_Monitoring_Tuning_Support_2025.pdf"

echo "Uploading 44/68: contracts/SIGNED_-_Mercury_KYC_EDD_PM_Support_bM5AXZQ.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Mercury_KYC_EDD_PM_Support_bM5AXZQ.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Mercury_KYC_EDD_PM_Support_bM5AXZQ.pdf"

echo "Uploading 45/68: contracts/SIGNED_-_Meta_2025_ulRtkRi.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Meta_2025_ulRtkRi.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Meta_2025_ulRtkRi.pdf"

echo "Uploading 46/68: contracts/SIGNED_-_Modern_Foundry_Compliance_Program_Buildout_EqbHcOY.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Modern_Foundry_Compliance_Program_Buildout_EqbHcOY.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Modern_Foundry_Compliance_Program_Buildout_EqbHcOY.pdf"

echo "Uploading 47/68: contracts/SIGNED_-_Motive_Compliance_Program_Buildout_vywbcTM.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Motive_Compliance_Program_Buildout_vywbcTM.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Motive_Compliance_Program_Buildout_vywbcTM.pdf"

echo "Uploading 48/68: contracts/SIGNED_-_MtFuji_Risk_Management_Process_QLb0gUk.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_MtFuji_Risk_Management_Process_QLb0gUk.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_MtFuji_Risk_Management_Process_QLb0gUk.pdf"

echo "Uploading 49/68: contracts/SIGNED_-_Paxos_AML_Operational_Support_2025_-_Extension_qJoXbiv.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Paxos_AML_Operational_Support_2025_-_Extension_qJoXbiv.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Paxos_AML_Operational_Support_2025_-_Extension_qJoXbiv.pdf"

echo "Uploading 50/68: contracts/SIGNED_-_Paxos_AML_Ops_Support_2025_777RaFx.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Paxos_AML_Ops_Support_2025_777RaFx.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Paxos_AML_Ops_Support_2025_777RaFx.pdf"

echo "Uploading 51/68: contracts/SIGNED_-_Paxos_DFS_Project_Plan_Support_M8WvqoB.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Paxos_DFS_Project_Plan_Support_M8WvqoB.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Paxos_DFS_Project_Plan_Support_M8WvqoB.pdf"

echo "Uploading 52/68: contracts/SIGNED_-_Paxos_FC_Risk_Assessment_ubchWwA.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Paxos_FC_Risk_Assessment_ubchWwA.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Paxos_FC_Risk_Assessment_ubchWwA.pdf"

echo "Uploading 53/68: contracts/SIGNED_-_Paxos_Model_Gov_Staff_Augmentation_2025_aE3iyd0.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Paxos_Model_Gov_Staff_Augmentation_2025_aE3iyd0.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Paxos_Model_Gov_Staff_Augmentation_2025_aE3iyd0.pdf"

echo "Uploading 54/68: contracts/SIGNED_-_Paxos_Outsourced_Operational_Support_2025_05_22_CHPYmdP.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Paxos_Outsourced_Operational_Support_2025_05_22_CHPYmdP.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Paxos_Outsourced_Operational_Support_2025_05_22_CHPYmdP.pdf"

echo "Uploading 55/68: contracts/SIGNED_-_Qbit_BSA_AML_Independent_Assessment_Mo9YuNF.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Qbit_BSA_AML_Independent_Assessment_Mo9YuNF.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Qbit_BSA_AML_Independent_Assessment_Mo9YuNF.pdf"

echo "Uploading 56/68: contracts/SIGNED_-_Ramp_Compliance_Support_ZTWmFz0.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Ramp_Compliance_Support_ZTWmFz0.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Ramp_Compliance_Support_ZTWmFz0.pdf"

echo "Uploading 57/68: contracts/SIGNED_-_Ramp_Ops_Support_Apr_2025_G8Pl7zU.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Ramp_Ops_Support_Apr_2025_G8Pl7zU.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Ramp_Ops_Support_Apr_2025_G8Pl7zU.pdf"

echo "Uploading 58/68: contracts/SIGNED_-_Ripple_Bridger_Implementation_Support_2025_WPlGvDs.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Ripple_Bridger_Implementation_Support_2025_WPlGvDs.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Ripple_Bridger_Implementation_Support_2025_WPlGvDs.pdf"

echo "Uploading 59/68: contracts/SIGNED_-_Ripple_Persona_Testing_l38j0eW.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Ripple_Persona_Testing_l38j0eW.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Ripple_Persona_Testing_l38j0eW.pdf"

echo "Uploading 60/68: contracts/SIGNED_-_Ripple_Project_Highrise_gtsBKCV.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Ripple_Project_Highrise_gtsBKCV.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Ripple_Project_Highrise_gtsBKCV.pdf"

echo "Uploading 61/68: contracts/SIGNED_-_Ripple_WC_Tuning_and_CMS_U3HGUGh.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Ripple_WC_Tuning_and_CMS_U3HGUGh.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Ripple_WC_Tuning_and_CMS_U3HGUGh.pdf"

echo "Uploading 62/68: contracts/SIGNED_-_Salsa_Compliance_Support_2025_4HBi0rJ.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Salsa_Compliance_Support_2025_4HBi0rJ.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Salsa_Compliance_Support_2025_4HBi0rJ.pdf"

echo "Uploading 63/68: contracts/SIGNED_-_Sure_2024_AML_and_ACH_Audit.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Sure_2024_AML_and_ACH_Audit.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Sure_2024_AML_and_ACH_Audit.pdf"

echo "Uploading 64/68: contracts/SIGNED_-_Trustly_IA_MultiYear_2024_to_2026.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Trustly_IA_MultiYear_2024_to_2026.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Trustly_IA_MultiYear_2024_to_2026.pdf"

echo "Uploading 65/68: contracts/SIGNED_-_Yoshi_Compliance_Program_Buildout_YJ7BHU6.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Yoshi_Compliance_Program_Buildout_YJ7BHU6.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Yoshi_Compliance_Program_Buildout_YJ7BHU6.pdf"

echo "Uploading 66/68: contracts/SIGNED_-_Zeal_Ongoing_Compliance_Support_CXGyd6e.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_Zeal_Ongoing_Compliance_Support_CXGyd6e.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_Zeal_Ongoing_Compliance_Support_CXGyd6e.pdf"

echo "Uploading 67/68: contracts/SIGNED_-__Conduit_Compliance_Operations_Support_euTwAId.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-__Conduit_Compliance_Operations_Support_euTwAId.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-__Conduit_Compliance_Operations_Support_euTwAId.pdf"

echo "Uploading 68/68: contracts/SIGNED_-_eBAY_Final_CO_2024_gHaER60.pdf"
gsutil cp "$MEDIA_ROOT/contracts/SIGNED_-_eBAY_Final_CO_2024_gHaER60.pdf" "gs://$BUCKET_NAME/contracts/SIGNED_-_eBAY_Final_CO_2024_gHaER60.pdf"

echo "
✅ Migration complete!"
echo "Verifying files in GCS..."
gsutil ls -r gs://$BUCKET_NAME/contracts/ | wc -l
