# Generated by Django 5.2.6 on 2025-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='raw_extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw extracted data from PDF parsing for future reference and debugging'),
        ),
    ]
