# Generated by Django 5.2.6 on 2025-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contract_raw_extracted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total contract value', max_digits=15, null=True),
        ),
    ]
