# Generated by Django 5.2.6 on 2025-09-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contract_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, help_text='Contract end date (null for ongoing contracts)', null=True),
        ),
    ]
