# Generated by Django 5.2.6 on 2025-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, help_text='Contract start date', null=True),
        ),
    ]
