# Generated by Django 5.2.6 on 2025-09-24 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contract_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractClarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Field requiring clarification (e.g., 'start_date', 'client_name')", max_length=100)),
                ('ai_question', models.TextField(help_text='Question generated by AI for clarification')),
                ('context_snippet', models.TextField(help_text='Relevant text excerpt from the contract')),
                ('page_number', models.IntegerField(blank=True, help_text='Page number where context was found', null=True)),
                ('user_answer', models.TextField(blank=True, help_text="User's response to the clarification question", null=True)),
                ('answered', models.BooleanField(default=False, help_text='Whether the question has been answered')),
                ('answered_at', models.DateTimeField(blank=True, help_text='When the question was answered', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the clarification was created')),
                ('contract', models.ForeignKey(help_text='Contract requiring clarification', on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='core.contract')),
            ],
            options={
                'verbose_name': 'Contract Clarification',
                'verbose_name_plural': 'Contract Clarifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
