# Generated by Django 5.2.6 on 2025-09-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contractclarification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('needs_clarification', 'Needs Clarification'), ('error', 'Error')], default='uploaded', help_text='Processing status', max_length=20),
        ),
    ]
