# Generated by Django 5.2.6 on 2025-09-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='po_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated for this PO in USD', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='po_number',
            field=models.CharField(blank=True, help_text="Client's Purchase Order number", max_length=100, null=True),
        ),
    ]
