# Generated by Django 5.2.6 on 2025-09-26 01:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contracttype_contract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_contra_search__e53eed_gin'),
        ),
    ]
