# Generated by Django 5.2.6 on 2025-09-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contract_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmilestone',
            name='qbo_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='paymentmilestone',
            name='qbo_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmilestone',
            name='qbo_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
