# Generated by Django 5.2.6 on 2025-09-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paymentmilestone_qbo_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmilestone',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date when invoice is issued', null=True),
        ),
    ]
