# Generated by Django 5.2.6 on 2025-09-26 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paymentmilestone_invoice_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(help_text='HubSpot deal record ID', max_length=50, unique=True)),
                ('deal_name', models.CharField(help_text='Name of the deal', max_length=255)),
                ('stage', models.CharField(help_text='Current deal stage', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Deal amount', max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', help_text='Deal currency', max_length=10)),
                ('close_date', models.DateField(blank=True, help_text='Expected or actual close date', null=True)),
                ('letter_sent_date', models.DateField(blank=True, help_text='Date when engagement letter was sent', null=True)),
                ('owner', models.CharField(blank=True, help_text='Deal owner', max_length=255, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Store full row for debugging and future reference', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When deal was uploaded')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the deal', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HubSpot Deal',
                'verbose_name_plural': 'HubSpot Deals',
                'ordering': ['-close_date', '-letter_sent_date'],
            },
        ),
        migrations.CreateModel(
            name='HubSpotDealMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True, help_text='When match was created')),
                ('confidence_note', models.TextField(blank=True, help_text='Notes about match confidence or reasoning')),
                ('is_active', models.BooleanField(default=True, help_text='For soft delete/reassignment')),
                ('contract', models.ForeignKey(help_text='Associated contract', on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_matches', to='core.contract')),
                ('deal', models.ForeignKey(help_text='Associated HubSpot deal', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.hubspotdeal')),
                ('matched_by', models.ForeignKey(help_text='User who created the match', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HubSpot Deal Match',
                'verbose_name_plural': 'HubSpot Deal Matches',
                'ordering': ['-matched_at'],
                'unique_together': {('deal', 'contract', 'is_active')},
            },
        ),
    ]
