# Generated by Django 5.2.6 on 2025-10-08 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hubspotdeal_hubspotdealmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAgingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='When the data was uploaded')),
                ('file_name', models.CharField(help_text='Original filename of the uploaded Excel file', max_length=255)),
                ('customer_name', models.CharField(help_text='Customer/client name', max_length=255)),
                ('invoice_number', models.CharField(help_text='Invoice reference number', max_length=100)),
                ('invoice_date', models.DateField(help_text='Date when invoice was issued')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount', max_digits=15)),
                ('days_overdue', models.IntegerField(default=0, help_text='Number of days past due date')),
                ('aging_bucket', models.CharField(help_text='Aging category (Current, 1-30, 31-60, 61-90, 90+)', max_length=50)),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('payment_status', models.CharField(blank=True, help_text='Payment status (if available)', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this AR data', on_delete=django.db.models.deletion.CASCADE, related_name='ar_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AR Aging Data',
                'verbose_name_plural': 'AR Aging Data',
                'ordering': ['-upload_date', 'customer_name'],
                'indexes': [models.Index(fields=['customer_name'], name='ar_customer_idx'), models.Index(fields=['aging_bucket'], name='ar_aging_idx'), models.Index(fields=['upload_date'], name='ar_upload_idx'), models.Index(fields=['invoice_date'], name='ar_inv_date_idx'), models.Index(fields=['due_date'], name='ar_due_date_idx')],
            },
        ),
    ]
