# Generated by Django 5.2.6 on 2025-10-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_ar_aging_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aragingdata',
            name='transaction_type',
            field=models.CharField(default='Invoice', help_text='Transaction type (Invoice, Payment, Credit Memo, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aragingdata',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date', null=True),
        ),
        migrations.AlterField(
            model_name='aragingdata',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date when invoice was issued', null=True),
        ),
        migrations.AlterField(
            model_name='aragingdata',
            name='invoice_number',
            field=models.CharField(blank=True, default='', help_text='Invoice reference number', max_length=100),
        ),
    ]
